name: release gdsfactory installer
on:
  release:
    types: [created, published]
  push:
    branches: [master]
    tags: [v*]

jobs:
  release_add:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 12
      matrix:
        python-version: ["3.8"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.8"
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: anaconda-client-env
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: constructor build
        run: |
          mamba install constructor
          constructor .
          pwd
          ls
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: false
          files: |
            gdsfactory-5.47.0-Linux-x86_64.sh
            gdsfactory-5.47.0-Windows-x86_64.exe
            gdsfactory-5.47.0-MacOSX-x86_64.pkg
