# https://github.com/conda-incubator/setup-miniconda
# https://github.com/actions/starter-workflows/blob/main/ci/python-package-conda.yml
name: Test plugins

on:
  pull_request:
  push:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.10.1
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: anaconda-client-env
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make gdslib plugins
          make install
          pip install -r requirements_full.txt
      - name: Test with pytest
        env:
          TIDY3D_USER: ${{ secrets.TIDY3D_EMAIL }}
          TIDY3D_PASS: ${{ secrets.TIDY3D_PASSWORD }}
        run: |
          mkdir -p $HOME/.tidy3d
          echo ${{ secrets.TIDY3D_AUTH }} > $HOME/.tidy3d/auth.json
          make test-plugins
